parameters:
  - name: openTofuDir
    type: string

  - name: openTofuPlanFilepath
    type: string

stages:
  - stage: ValidateAndPlanStage
    displayName: Validate and Plan Stage
    jobs:
      - template: /v1/templates/jobs/opentofu/validate_and_plan.yml
        parameters:
          openTofuDir: ${{ parameters.openTofuDir }}
          openTofuPlanFilepath: ${{ parameters.openTofuPlanFilepath }}

      - template: /v1/templates/jobs/opentofu/apply.yml
        parameters:
          openTofuPlanFilepath: ${{ parameters.openTofuPlanFilepath }}
