parameters:
  - name: openTofuDir
    type: string

  - name: openTofuPlanFilepath
    type: string

stages:
  - template: /v1/templates/stages/opentofu/validate_and_plan.yml
    parameters:
      openTofuDir: ${{ parameters.openTofuDir }}
      openTofuPlanFilepath: ${{ parameters.openTofuPlanFilepath }}
