parameters:
  - name: openTofuDir
    type: string
    default: .

stages:
  - template: /.azuredevops/v1/templates/stages/opentofu/validate_and_plan.yml
    parameters:
      openTofuDir: ${{ parameters.openTofuDir }}
